version: '2'
services:
  jhipstertest7-app:
    image: jhipstertest7
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstertest7-postgresql:5432/jhipstertest7
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstertest7-postgresql:
    extends:
      file: postgresql.yml
      service: jhipstertest7-postgresql
